### ISSUE TITLE
Feature request: tags

### ISSUE THREAD

**Issue by rdouma** [iKenndac/500px-Aperture-Uploader#1]
It would be great if tags could be set directly from the plug-in. And even better if they would be initialized with the Aperture tags assigned :-)

**Comment by iKenndac** [comment]
Great idea - I'll look into it!

**Comment by rdouma** [comment]
Awesome! :-)

**Comment by iKenndac** [comment]
It appears that the 500px API doesn't support setting tags at this time - could be wrong though. I'll email them for clarification.

**Comment by rdouma** [comment]
Wow, I see you're on top of it :-) Thanks for keeping me posted.

**Comment by wiiiimm** [comment]
hope 500px can add tag support in API soon...

**Comment by iKenndac** [comment]
Me too! You should email them and ask for it. The more people that do, the faster it'll happen!

**Comment by wiiiimm** [comment]
btw, doesn't the photo file itself contains the keywords / tags anyway?
the tags are there when i export files manually from Aperture and upload them via web interface.

**Comment by wiiiimm** [comment]
i tweeted them @500px 
hope more people can see this and contact 500px regarding it.
thanks for the plugin :)

**Comment by wiiiimm** [comment]
and i think i just got you a respond: @iKenndac API does support tags, the docs are lagging behind though. I'll get to fixing that situation as soon as.

**Comment by rdouma** [comment]
Isn't the internet an amazing thing? :-)

**Comment by freeatnet** [comment]
@williamli Hi. That was me on Twitter. I'm with 500px and we do indeed have API support for tags. We're late on documenting it though, but I intend on getting to fixing it as soon as I can.

**Comment by wiiiimm** [comment]
hi @freeatnet are you working with 500px?

**Comment by iKenndac** [comment]
I'd like to politely point out that this is an issue tracker, not a chat client or Twitter. Only messages actually helpful to the issue at hand please, since I get an email each time someone comments.

**Comment by glaurent** [comment]
Hi,

I was about to try adding a preference setting to filter keywords on export but just realised that keywords/tags aren't currently supported :-). Has there been any update on this since then ? If the API is available (Google couldn't find anything), I'm willing to help.
