### ISSUE TITLE
Growl notification error causing a crash

### ISSUE THREAD

**Issue by nlecam** [iKenndac/500px-Aperture-Uploader#14]
Using last 500px-Aperture-Iploader version (0.4) When Aperture finishes uploading tu 500px.com his photos, I suddenly have a crash with notification about a Growl error encountered. I use the "let an alert appear when a cliché is uploaded" feature.

**Comment by iKenndac** [comment]
Hey, I can't reproduce this bug for the life of me. However, I've rewritten the Growl integration a little bit so hopefully 0.5 will fix it.

**Comment by nlecam** [comment]
Thank you very much. I'll test it and report to you.
