### ISSUE TITLE
uploaded photo is apparently not really uploaded

### ISSUE THREAD

**Issue by glaurent** [iKenndac/500px-Aperture-Uploader#23]
Fresh install of v0.5 (tried installing from the github project first, but it wouldn't let me log in). I tried uploading a photo, it went successfully according to the logs but the photo doesn't appear on my portfolio.

I know there's some processing done by 500px before the photo is available, but it's been 90mn and the photo is still not there. It was uploaded as a private photo.

**Comment by iKenndac** [comment]
The 500px queue can sometimes be quite long — a little while ago it was running at over 24 hours for a couple of days. If the photo doesn't show up by tomorrow I can take a look at it.

**Comment by glaurent** [comment]
It's still not there - here's the URL : http://500px.com/photo/6579456

**Comment by iKenndac** [comment]
Well, I'm not going to be able to view a private photo no matter what happens!

I spoke to the guys at 500px and they were having issues with one of their processing machines, which was causing the occasional lost photo (I experienced it myself a couple of days ago).

The API was never returning anything but success, and there's literally nothing I can do in this sort of the situation — I have to trust that when the 500px API says "success", it means it.

**Comment by glaurent** [comment]
I tried again, it seems that the problem occurs only if the photo is uploaded as private.
