### ISSUE TITLE
Plugin doesn't appear to work in Aperture 3.4

### ISSUE THREAD

**Issue by iKenndac** [iKenndac/500px-Aperture-Uploader#29]
Aperture 3.4 is sandboxed, which causes problems.

**Comment by georgeharker** [comment]
Any ideas how to fix this? 

It doesn't seem to be as simple as signing the plugin. 

George

**Comment by iKenndac** [comment]
Yes, I'm working on it.

**Comment by georgeharker** [comment]
Thanks. I'll grab the patch
