### ISSUE TITLE
"Open 500px.com" after export

### ISSUE THREAD

**Issue by iKenndac** [iKenndac/500px-Aperture-Uploader#3]
An option to have the plugin automatically take you to your uploaded photos in your browser.

**Comment by ashfurrow** [comment]
This could be an action associated with Growl Notifications; use case is when you click on the Growl Notification, you get taken to your photos in the browser.

**Comment by iKenndac** [comment]
Now _that_ is a kickass idea!

**Comment by ashfurrow** [comment]
I've got a fork of this - mind if I tackle this one, or would you like to?

**Comment by iKenndac** [comment]
Go right ahead! The more the merrier :-)

Disclaimer: I threw this together in a few hours so the code is pretty crappy. Since the project has gained quite a lot of attention I intend to refactor it to be better!

**Comment by ashfurrow** [comment]
No problem - I'll try to add the Growl Notifications in such a way that it shouldn't be a problem to merge back in with any refactoring changes.

**Comment by iKenndac** [comment]
Now in code as part of the Growl notifications. Thanks!
